#######################
## GATEWAY SETTINGS
#######################
[general]
    logging_config = "/etc/faspio-gateway/logging.toml"

[[bridge]]
        name = "FTP"
    [bridge.local]
        protocol = "tcp"
        bind_address = "0.0.0.0"
            port = "21-22"

    [bridge.forward]
        protocol = "fasp"
            host = "gw2"
            port = "21-22"
